apiVersion: v1
kind: ConfigMap
metadata:
  name: products-api-config
  namespace: default
data:
  application.properties: |
    spring.datasource.url=jdbc:postgresql://products-db-0.products-db.default.svc.cluster.local:5432/postgres
    spring.datasource.username=postgres
